"""Milestone 6 — Claude analysis of the M3 analytics.

## What this is, and what it deliberately is not

Helios asks Claude to **describe** a portfolio it can already measure. Every fact the model is
given comes from the M3 replay and the M5 news store; the model adds structure and prose, not
data. Concretely:

* **No forecasts, no buy/sell/hold.** The output schema has no price target, no rating, and no
  action field, so there is nowhere for one to go. The system prompt says so too, but the schema
  is the enforcement.
* **Every observation must cite its evidence.** `evidence` is a required schema field and must
  quote a figure from the supplied analytics. An observation that cannot cite one is invalid
  output, not a softly-worded guess.
* **Statuses travel with the numbers.** Metrics M3 declared `insufficient_data` or `unavailable`
  are passed through with that status attached, so the model sees what is unknown rather than
  inferring a value from an absent one.
* **Raw-first.** The exact request and response are stored in `ai_runs` before anything is
  parsed, so any published insight can be traced back to the numbers behind it.

This is descriptive analysis for personal use. It is not investment advice, and the disclosure
travels with the output through the API, the CLI and the dashboard.
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Protocol

from anthropic import (
    APIConnectionError,
    APIStatusError,
    AsyncAnthropic,
    RateLimitError,
)
from anthropic.types.beta import BetaTextBlock

from .config import Settings
from .models import AiObservation, AiRun, NewsItem
from .performance import MetricValue, NoPerformanceDataError, PerformanceReport
from .portfolio_repository import PortfolioRepository
from .rate_limit import Clock, SystemClock

PROVIDER = "anthropic"
DISCLOSURE = (
    "Descriptive analysis of your own portfolio data, generated by an AI model. "
    "It is not investment advice, not a recommendation to buy or sell, and not a forecast. "
    "Every statement is derived from figures Helios reconstructed from your Trading 212 history."
)

SEVERITIES = ("info", "notable", "elevated")
CATEGORIES = (
    "concentration",
    "risk",
    "performance",
    "attribution",
    "data_quality",
    "news",
)

SYSTEM_PROMPT = """\
You are a portfolio analyst writing a factual briefing for the owner of the portfolio.

You will be given a JSON document of metrics Helios computed from the owner's own brokerage
history, plus recent headlines from sources the owner configured. Your job is to describe what
those numbers show.

Hard rules:
- Use ONLY the supplied figures. Never introduce a number, price, ratio or fact that is not in
  the input. If you want to say something you cannot support from the input, omit it.
- Every observation must quote the specific figure it rests on, in the `evidence` field. If you
  cannot quote a figure, do not make the observation.
- Metrics carry a `status`. When the status is not "ok", the metric is UNKNOWN — say it is
  unavailable, never infer or estimate a value for it.
- Do NOT give investment advice. No buy/sell/hold, no price targets, no forecasts, no
  suggestions to rebalance, and no opinions on whether a holding is a good investment.
- Describe risk factually ("the top holding is 62% of NAV") rather than judgementally ("this is
  dangerously concentrated").
- Headlines are supplied for context only. You may note that coverage exists for a holding; you
  may not infer a price impact from a headline.

Rank observations by how much they would change the owner's understanding of their portfolio,
most significant first."""

OUTPUT_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "summary": {
            "type": "string",
            "description": "Two or three sentences describing the portfolio's current shape.",
        },
        "observations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "category": {"type": "string", "enum": list(CATEGORIES)},
                    "t212_ticker": {
                        "type": ["string", "null"],
                        "description": "Holding this concerns, or null if portfolio-wide.",
                    },
                    "headline": {"type": "string"},
                    "detail": {"type": "string"},
                    "evidence": {
                        "type": "string",
                        "description": "The specific figure from the input this rests on.",
                    },
                    "severity": {"type": "string", "enum": list(SEVERITIES)},
                },
                "required": [
                    "category",
                    "t212_ticker",
                    "headline",
                    "detail",
                    "evidence",
                    "severity",
                ],
                "additionalProperties": False,
            },
        },
        "unavailable_metrics": {
            "type": "array",
            "items": {"type": "string"},
            "description": "Metrics the input reported as unavailable or insufficient.",
        },
    },
    "required": ["summary", "observations", "unavailable_metrics"],
    "additionalProperties": False,
}


class AiUnavailableError(RuntimeError):
    """Raised when analysis cannot run at all — no key, or no analytics to describe."""


@dataclass(frozen=True)
class AiObservationView:
    rank: int
    category: str
    t212_ticker: str | None
    headline: str
    detail: str
    evidence: str
    severity: str


@dataclass(frozen=True)
class AiAnalysis:
    status: str
    as_of: datetime
    model: str
    served_by_model: str | None
    effort: str | None
    summary: str | None
    observations: list[AiObservationView]
    unavailable_metrics: list[str]
    input_tokens: int | None
    output_tokens: int | None
    cache_read_tokens: int | None
    disclosure: str
    detail: str | None = None


@dataclass(frozen=True)
class AiBrief:
    """What the model is told and the shape its answer must take."""

    system: str
    schema: dict[str, Any]
    instruction: str


ANALYSIS_BRIEF = AiBrief(
    system=SYSTEM_PROMPT,
    schema=OUTPUT_SCHEMA,
    instruction="Analyse this portfolio. Respond only with the JSON schema.",
)


class AiClient(Protocol):
    async def analyse(
        self, payload: dict[str, Any], *, brief: AiBrief | None = None
    ) -> AiClientResult: ...


@dataclass(frozen=True)
class AiClientResult:
    status: str
    model: str
    served_by_model: str | None
    parsed: dict[str, Any] | None
    raw_response: dict[str, Any]
    input_tokens: int | None
    output_tokens: int | None
    cache_read_tokens: int | None
    detail: str | None = None


class NullAiClient:
    """Used when no API key is configured; keeps the whole pipeline runnable offline."""

    async def analyse(
        self, payload: dict[str, Any], *, brief: AiBrief | None = None
    ) -> AiClientResult:
        del payload, brief
        return AiClientResult(
            status="unavailable",
            model="none",
            served_by_model=None,
            parsed=None,
            raw_response={},
            input_tokens=None,
            output_tokens=None,
            cache_read_tokens=None,
            detail=(
                "No Anthropic API key configured. Set HELIOS_ANTHROPIC_API_KEY to enable "
                "AI analysis."
            ),
        )


class ClaudeAiClient:
    """Calls the Messages API with structured outputs and adaptive thinking."""

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        key = settings.anthropic_api_key
        self._client = (
            AsyncAnthropic(
                api_key=key.get_secret_value(), timeout=settings.anthropic_timeout_seconds
            )
            if key is not None
            else None
        )

    async def aclose(self) -> None:
        if self._client is not None:
            await self._client.close()

    async def analyse(
        self, payload: dict[str, Any], *, brief: AiBrief | None = None
    ) -> AiClientResult:
        if self._client is None:
            return await NullAiClient().analyse(payload)
        settings = self._settings
        brief = brief or ANALYSIS_BRIEF
        try:
            response = await self._client.beta.messages.create(
                model=settings.anthropic_model,
                max_tokens=settings.anthropic_max_tokens,
                # Adaptive thinking: Claude decides how much reasoning each portfolio needs.
                thinking={"type": "adaptive"},
                output_config={
                    "effort": settings.anthropic_effort,
                    "format": {"type": "json_schema", "schema": brief.schema},
                },
                # The system prompt is byte-stable across runs, so it caches; the portfolio
                # payload that follows is what varies.
                system=[
                    {
                        "type": "text",
                        "text": brief.system,
                        "cache_control": {"type": "ephemeral"},
                    }
                ],
                # Opus 5's classifiers can decline a request; this re-runs it server-side
                # rather than surfacing a refusal.
                betas=["server-side-fallback-2026-06-01"],
                fallbacks=[{"model": settings.anthropic_fallback_model}],
                messages=[
                    {
                        "role": "user",
                        "content": (
                            brief.instruction
                            + "\n\n"
                            + json.dumps(payload, indent=2, sort_keys=True)
                        ),
                    }
                ],
            )
        except RateLimitError as error:
            return _client_error("rate_limited", error)
        except APIStatusError as error:
            return _client_error("api_error", error)
        except APIConnectionError as error:
            return _client_error("unreachable", error)

        raw = response.model_dump(mode="json")
        served_by = _served_by(response)
        usage = getattr(response, "usage", None)
        if response.stop_reason == "refusal":
            return AiClientResult(
                status="refused",
                model=settings.anthropic_model,
                served_by_model=served_by,
                parsed=None,
                raw_response=raw,
                input_tokens=getattr(usage, "input_tokens", None),
                output_tokens=getattr(usage, "output_tokens", None),
                cache_read_tokens=getattr(usage, "cache_read_input_tokens", None),
                detail="The model declined this request and the fallback did not answer either.",
            )
        # `content` is a union of block types; only text blocks carry the structured payload.
        text = "".join(block.text for block in response.content if isinstance(block, BetaTextBlock))
        try:
            parsed = json.loads(text)
        except ValueError:
            return AiClientResult(
                status="unparseable",
                model=settings.anthropic_model,
                served_by_model=served_by,
                parsed=None,
                raw_response=raw,
                input_tokens=getattr(usage, "input_tokens", None),
                output_tokens=getattr(usage, "output_tokens", None),
                cache_read_tokens=getattr(usage, "cache_read_input_tokens", None),
                detail="The model's response was not valid JSON.",
            )
        return AiClientResult(
            status="ok",
            model=settings.anthropic_model,
            served_by_model=served_by,
            parsed=parsed if isinstance(parsed, dict) else None,
            raw_response=raw,
            input_tokens=getattr(usage, "input_tokens", None),
            output_tokens=getattr(usage, "output_tokens", None),
            cache_read_tokens=getattr(usage, "cache_read_input_tokens", None),
        )


def _client_error(status: str, error: Exception) -> AiClientResult:
    # Only the class name travels — an API error body can echo request content.
    return AiClientResult(
        status=status,
        model="unknown",
        served_by_model=None,
        parsed=None,
        raw_response={},
        input_tokens=None,
        output_tokens=None,
        cache_read_tokens=None,
        detail=error.__class__.__name__,
    )


def _served_by(response: Any) -> str | None:
    """Which model actually answered — a fallback may have taken over."""
    usage = getattr(response, "usage", None)
    iterations = getattr(usage, "iterations", None) or []
    for entry in iterations:
        if getattr(entry, "type", None) == "fallback_message":
            return str(getattr(response, "model", "")) or None
    return None


# ---------------------------------------------------------------------------
# Prompt payload — the only facts the model ever sees
# ---------------------------------------------------------------------------


def _metric(value: MetricValue) -> dict[str, Any]:
    """Serialise a metric with its status, so 'unknown' stays visibly unknown."""
    if value.status != "ok" or value.value is None:
        return {"status": value.status, "value": None, "note": value.detail}
    return {"status": "ok", "value": round(value.value, 6), "observations": value.observations}


def build_payload(
    report: PerformanceReport, news: list[NewsItem], *, max_news: int
) -> dict[str, Any]:
    """Flatten the analytics and headlines into the exact JSON the model receives."""
    return {
        "window": {"start": str(report.start_date), "end": str(report.end_date)},
        "conventions": {
            "flow_timing": report.flow_timing,
            "annualization_days": report.annualization_days,
            "base_currency": "EUR",
        },
        "returns": {
            "cumulative_twr": _metric(report.cumulative_twr),
            "annualized": _metric(report.annualized_return),
            "xirr": _metric(report.xirr),
        },
        "risk": {
            "volatility": _metric(report.volatility),
            "downside_volatility": _metric(report.downside_volatility),
            "sharpe": _metric(report.sharpe),
            "sortino": _metric(report.sortino),
            "calmar": _metric(report.calmar),
            "max_drawdown": _metric(report.max_drawdown),
            "time_underwater_days": _metric(report.time_underwater_days),
            "recovery_days": _metric(report.recovery_days),
            "var_95_1d": _metric(report.var_95_1d),
            "cvar_95_1d": _metric(report.cvar_95_1d),
            "var_99_10d": _metric(report.var_99_10d),
            "cvar_99_10d": _metric(report.cvar_99_10d),
        },
        "concentration": {
            "hhi": _metric(report.hhi),
            "effective_positions": _metric(report.effective_number_of_positions),
            "top5_weight": _metric(report.top5_weight),
        },
        "contributions": [
            {
                "ticker": item.key,
                "weight": round(item.weight, 6),
                "status": item.status,
                "return": None if item.return_value is None else round(item.return_value, 6),
                "contribution": None if item.contribution is None else round(item.contribution, 6),
            }
            for item in report.contributions
        ],
        "benchmarks": [
            {
                "label": item.benchmark.label,
                "symbol": item.benchmark.providerSymbol
                if hasattr(item.benchmark, "providerSymbol")
                else item.benchmark.provider_symbol,
                "beta": _metric(item.beta),
                "correlation": _metric(item.correlation),
                "tracking_error": _metric(item.tracking_error),
            }
            for item in report.beta_vs_benchmarks
        ],
        "correlation_clusters": {
            "status": report.correlation_clusters.status,
            "cluster_count": report.correlation_clusters.cluster_count,
            "detail": report.correlation_clusters.detail,
            "assignments": [
                {"ticker": a.key, "cluster": a.cluster, "weight": round(a.weight, 6)}
                for a in report.correlation_clusters.assignments
            ],
        },
        "attribution": {
            "status": report.attribution.status,
            "detail": report.attribution.detail,
        },
        "factor_exposure": {
            "status": report.ff5_momentum_regression.status,
            "detail": report.ff5_momentum_regression.detail,
            "r_squared": report.ff5_momentum_regression.r_squared,
            "coefficients": report.ff5_momentum_regression.coefficients,
        },
        "passive_counterfactual": {
            "status": report.passive_counterfactual.status,
            "benchmark": report.passive_counterfactual.benchmark_label,
            "invested_eur": _decimal(report.passive_counterfactual.invested_eur),
            "passive_value_eur": _decimal(report.passive_counterfactual.final_value_eur),
            "actual_nav_eur": _decimal(report.passive_counterfactual.actual_nav_eur),
            "detail": report.passive_counterfactual.detail,
        },
        "method_notes": report.notes,
        "recent_news": [
            {
                "ticker": item.t212_ticker,
                "source": item.source_label,
                "headline": item.headline,
                "published_at": item.published_at.isoformat() if item.published_at else None,
            }
            for item in news[:max_news]
        ],
    }


def _decimal(value: object) -> str | None:
    return None if value is None else str(value)


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------


class AiAnalysisService:
    def __init__(
        self,
        repository: PortfolioRepository,
        settings: Settings,
        performance_service: Any,
        client: AiClient | None = None,
        clock: Clock | None = None,
    ) -> None:
        self._repository = repository
        self._settings = settings
        self._performance = performance_service
        self._client = client or NullAiClient()
        self._clock = clock or SystemClock()

    @property
    def enabled(self) -> bool:
        return self._settings.anthropic_api_key is not None

    async def analyse(self) -> AiAnalysis:
        now = self._clock.utcnow()
        try:
            report = await self._performance.get_report()
        except NoPerformanceDataError as error:
            raise AiUnavailableError(
                "No replayed analytics to describe. Run a performance replay first."
            ) from error
        news = await self._repository.list_news_items(limit=self._settings.ai_max_news_items)
        payload = build_payload(report, news, max_news=self._settings.ai_max_news_items)
        result = await self._client.analyse(payload)

        # Raw-first: the request and response land before anything is parsed out of them.
        run_id = await self._repository.insert_ai_run(
            AiRun(
                ts=now,
                provider=PROVIDER,
                model=result.model,
                effort=self._settings.anthropic_effort,
                status=result.status,
                detail=result.detail,
                prompt_json=payload,
                response_json=result.raw_response or None,
                input_tokens=result.input_tokens,
                output_tokens=result.output_tokens,
                cache_read_tokens=result.cache_read_tokens,
                served_by_model=result.served_by_model,
            )
        )

        if result.status != "ok" or result.parsed is None:
            return AiAnalysis(
                status=result.status,
                as_of=now,
                model=result.model,
                served_by_model=result.served_by_model,
                effort=self._settings.anthropic_effort,
                summary=None,
                observations=[],
                unavailable_metrics=[],
                input_tokens=result.input_tokens,
                output_tokens=result.output_tokens,
                cache_read_tokens=result.cache_read_tokens,
                disclosure=DISCLOSURE,
                detail=result.detail,
            )

        observations = parse_observations(result.parsed)
        await self._repository.insert_ai_observations(
            [
                AiObservation(
                    run_id=run_id,
                    rank=view.rank,
                    category=view.category,
                    t212_ticker=view.t212_ticker,
                    headline=view.headline,
                    detail=view.detail,
                    evidence=view.evidence,
                    severity=view.severity,
                )
                for view in observations
            ]
        )
        summary = result.parsed.get("summary")
        unavailable = result.parsed.get("unavailable_metrics")
        return AiAnalysis(
            status="ok",
            as_of=now,
            model=result.model,
            served_by_model=result.served_by_model,
            effort=self._settings.anthropic_effort,
            summary=summary if isinstance(summary, str) else None,
            observations=observations,
            unavailable_metrics=[m for m in unavailable or [] if isinstance(m, str)],
            input_tokens=result.input_tokens,
            output_tokens=result.output_tokens,
            cache_read_tokens=result.cache_read_tokens,
            disclosure=DISCLOSURE,
        )

    async def latest(self, kind: str = "analysis") -> AiAnalysis | None:
        """The most recent stored run, so the dashboard costs nothing to open."""
        run = await self._repository.latest_ai_run(kind)
        if run is None:
            return None
        observations = await self._repository.list_ai_observations(run.id)
        return AiAnalysis(
            status=run.status,
            as_of=run.ts,
            model=run.model,
            served_by_model=run.served_by_model,
            effort=run.effort,
            summary=_stored_summary(run),
            observations=[
                AiObservationView(
                    rank=row.rank,
                    category=row.category,
                    t212_ticker=row.t212_ticker,
                    headline=row.headline,
                    detail=row.detail,
                    evidence=row.evidence,
                    severity=row.severity,
                )
                for row in observations
            ],
            unavailable_metrics=_stored_unavailable(run),
            input_tokens=run.input_tokens,
            output_tokens=run.output_tokens,
            cache_read_tokens=run.cache_read_tokens,
            disclosure=DISCLOSURE,
            detail=run.detail,
        )


def parse_observations(
    parsed: dict[str, Any], *, categories: Sequence[str] = CATEGORIES
) -> list[AiObservationView]:
    """Keep only well-formed observations that cite evidence.

    An observation without evidence is dropped rather than shown: the citation is the whole
    mechanism by which an unfounded claim is visible, so an uncited one has no standing.
    """
    rows = parsed.get("observations")
    if not isinstance(rows, list):
        return []
    views: list[AiObservationView] = []
    for index, row in enumerate(rows, start=1):
        if not isinstance(row, dict):
            continue
        headline = row.get("headline")
        detail = row.get("detail")
        evidence = row.get("evidence")
        if not isinstance(headline, str) or not isinstance(detail, str):
            continue
        if not isinstance(evidence, str) or not evidence.strip():
            continue
        category = row.get("category")
        severity = row.get("severity")
        ticker = row.get("t212_ticker")
        views.append(
            AiObservationView(
                rank=index,
                category=(
                    category
                    if isinstance(category, str) and category in categories
                    else categories[0]
                ),
                t212_ticker=ticker if isinstance(ticker, str) and ticker else None,
                headline=headline.strip(),
                detail=detail.strip(),
                evidence=evidence.strip(),
                severity=severity if severity in SEVERITIES else "info",
            )
        )
    return views


def _stored_summary(run: AiRun) -> str | None:
    parsed = _stored_parsed(run)
    summary = parsed.get("summary") if parsed else None
    return summary if isinstance(summary, str) else None


def _stored_unavailable(run: AiRun) -> list[str]:
    parsed = _stored_parsed(run)
    values = parsed.get("unavailable_metrics") if parsed else None
    return [item for item in values or [] if isinstance(item, str)]


def _stored_parsed(run: AiRun) -> dict[str, Any] | None:
    response = run.response_json
    if not isinstance(response, dict):
        return None
    blocks = response.get("content")
    if not isinstance(blocks, list):
        return None
    for block in blocks:
        if isinstance(block, dict) and block.get("type") == "text":
            try:
                loaded = json.loads(block.get("text") or "")
            except ValueError:
                return None
            return loaded if isinstance(loaded, dict) else None
    return None
